services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local